<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class AmsProductsSeeder extends Seeder
{
    /**
     * Run the database seeds from ams_db.sql.
     */
    public function run(): void
    {
        $products = [
            [
                'product_id' => 1,
                'product_name' => 'Gear Oil',
                'additional_name' => 'Scooter Oil',
                'type' => '120ml',
                'brand' => 'Petron',
                'price' => 90,
                'quantity' => 9,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Petron Gear Oil 120ml',
            ],
            [
                'product_id' => 2,
                'product_name' => 'Motor Oil',
                'additional_name' => '2T',
                'type' => '200ml',
                'brand' => 'Petron',
                'price' => 40,
                'quantity' => 11,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Petron Motor Oil 200ml',
            ],
            [
                'product_id' => 3,
                'product_name' => 'Motor Oil',
                'additional_name' => '4T',
                'type' => '200ml',
                'brand' => 'Petron',
                'price' => 40,
                'quantity' => 6,
                'location' => 'Shelf A1',
                'image' => '/images/products/product_3.jpg',
                'description' => 'Petron Motor Oil 200ml',
            ],
            [
                'product_id' => 4,
                'product_name' => 'Motor Oil',
                'additional_name' => 'Havoline 2T',
                'type' => '200ml',
                'brand' => 'Caltex',
                'price' => 40,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Caltex Motor Oil 200ml',
            ],
            [
                'product_id' => 5,
                'product_name' => 'Break Fluid',
                'additional_name' => 'DOT-3',
                'type' => '300ml',
                'brand' => 'National',
                'price' => 100,
                'quantity' => 13,
                'location' => 'Shelf A1',
                'image' => '/images/products/brake-fluid.svg',
                'description' => 'National Break Fluid 300ml',
            ],
            [
                'product_id' => 6,
                'product_name' => 'Break Fluid',
                'additional_name' => 'DOT-3',
                'type' => '900ml',
                'brand' => 'National',
                'price' => 250,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/brake-fluid.svg',
                'description' => 'National Break Fluid 900ml',
            ],
            [
                'product_id' => 7,
                'product_name' => 'Break Fluid',
                'additional_name' => 'DOT-3',
                'type' => '500ml',
                'brand' => 'Prestone',
                'price' => 195,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/brake-fluid.svg',
                'description' => 'Prestone Break Fluid 500ml',
            ],
            [
                'product_id' => 8,
                'product_name' => 'Break Fluid',
                'additional_name' => 'DOT-3',
                'type' => '900ml',
                'brand' => 'Prestone',
                'price' => 280,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/brake-fluid.svg',
                'description' => 'Prestone Break Fluid 900ml',
            ],
            [
                'product_id' => 9,
                'product_name' => 'Diesel Engine Oil',
                'additional_name' => 'Delo Gold',
                'type' => '1L',
                'brand' => 'Caltex',
                'price' => 255,
                'quantity' => 14,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Caltex Diesel Engine Oil 1L',
            ],
            [
                'product_id' => 10,
                'product_name' => 'Gasoline Engine Oil',
                'additional_name' => 'Havoline 15W-40',
                'type' => '1L',
                'brand' => 'Caltex',
                'price' => 230,
                'quantity' => 12,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Caltex Gasoline Engine Oil 1L',
            ],
            [
                'product_id' => 11,
                'product_name' => 'Motor Oil',
                'additional_name' => 'Havoline 4T',
                'type' => '1L',
                'brand' => 'Caltex',
                'price' => 230,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Caltex Motor Oil 1L',
            ],
            [
                'product_id' => 12,
                'product_name' => 'Radiator Coolant',
                'additional_name' => 'Super Coolant',
                'type' => '1L',
                'brand' => 'Petron',
                'price' => 220,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/coolant.svg',
                'description' => 'Petron Radiator Coolant 1L',
            ],
            [
                'product_id' => 13,
                'product_name' => 'Gasoline Engine Oil',
                'additional_name' => 'Blaze Racing',
                'type' => '1L',
                'brand' => 'Petron',
                'price' => 210,
                'quantity' => 12,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Petron Gasoline Engine Oil 1L',
            ],
            [
                'product_id' => 14,
                'product_name' => 'Diesel Engine Oil',
                'additional_name' => 'Rev-X',
                'type' => '1L',
                'brand' => 'Petron',
                'price' => 190,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Petron Diesel Engine Oil 1L',
            ],
            [
                'product_id' => 15,
                'product_name' => 'Scooter Oil',
                'additional_name' => 'Sprint 4T',
                'type' => '800ml',
                'brand' => 'Petron',
                'price' => 215,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Petron Scooter Oil 800ml',
            ],
            [
                'product_id' => 16,
                'product_name' => 'Coolant',
                'additional_name' => 'Delo XLI',
                'type' => '1L',
                'brand' => 'Caltex',
                'price' => 180,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/coolant.svg',
                'description' => 'Caltex Coolant 1L',
            ],
            [
                'product_id' => 17,
                'product_name' => 'Motor Oil',
                'additional_name' => 'Sprint 4T',
                'type' => '1L',
                'brand' => 'Petron',
                'price' => 215,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Petron Motor Oil 1L',
            ],
            [
                'product_id' => 18,
                'product_name' => 'Diesel Engine Oil',
                'additional_name' => 'Rev-X',
                'type' => '1L',
                'brand' => 'Petron',
                'price' => 245,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Petron Diesel Engine Oil 1L',
            ],
            [
                'product_id' => 19,
                'product_name' => 'Transmission Fluid',
                'additional_name' => 'ATF',
                'type' => '1L',
                'brand' => 'Petron',
                'price' => 250,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Petron Transmission Fluid 1L',
            ],
            [
                'product_id' => 20,
                'product_name' => 'Motor Oil',
                'additional_name' => '2T',
                'type' => '1L',
                'brand' => 'Petron',
                'price' => 190,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Petron Motor Oil 1L',
            ],
            [
                'product_id' => 21,
                'product_name' => 'Transmission Fluid',
                'additional_name' => 'Dtec',
                'type' => '1L',
                'brand' => 'ZIP',
                'price' => 230,
                'quantity' => 12,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'ZIP Transmission Fluid 1L',
            ],
            [
                'product_id' => 22,
                'product_name' => 'Motor Oil',
                'additional_name' => 'Advance',
                'type' => '1L',
                'brand' => 'Shell',
                'price' => 230,
                'quantity' => 15,
                'location' => 'Shelf A1',
                'image' => '/images/products/oil.svg',
                'description' => 'Shell Motor Oil 1L',
            ],
            [
                'product_id' => 23,
                'product_name' => 'Bolt',
                'additional_name' => '',
                'type' => '3/8×3',
                'brand' => '',
                'price' => 12,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Bolt 3/8×3',
            ],
            [
                'product_id' => 24,
                'product_name' => 'Bolt',
                'additional_name' => '',
                'type' => '3/8×1',
                'brand' => '',
                'price' => 6,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Bolt 3/8×1',
            ],
            [
                'product_id' => 25,
                'product_name' => 'Bolt',
                'additional_name' => '',
                'type' => '3/8×3/4',
                'brand' => '',
                'price' => 6,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Bolt 3/8×3/4',
            ],
            [
                'product_id' => 26,
                'product_name' => 'Bolt',
                'additional_name' => '',
                'type' => '3/8×12',
                'brand' => '',
                'price' => 10,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Bolt 3/8×12',
            ],
            [
                'product_id' => 27,
                'product_name' => 'Nut',
                'additional_name' => '',
                'type' => '3/8',
                'brand' => '',
                'price' => 3,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Nut 3/8',
            ],
            [
                'product_id' => 28,
                'product_name' => 'Bolt',
                'additional_name' => '',
                'type' => '5/16×1',
                'brand' => '',
                'price' => 7,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Bolt 5/16×1',
            ],
            [
                'product_id' => 29,
                'product_name' => 'Bolt',
                'additional_name' => '',
                'type' => '5/16×1 1/2',
                'brand' => '',
                'price' => 8,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Bolt 5/16×1 1/2',
            ],
            [
                'product_id' => 30,
                'product_name' => 'Bolt',
                'additional_name' => '',
                'type' => '5/16×2',
                'brand' => '',
                'price' => 10,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Bolt 5/16×2',
            ],
            [
                'product_id' => 31,
                'product_name' => 'Bolt',
                'additional_name' => '',
                'type' => '5/16×3',
                'brand' => '',
                'price' => 11,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Bolt 5/16×3',
            ],
            [
                'product_id' => 32,
                'product_name' => 'Nut',
                'additional_name' => '',
                'type' => '5/16',
                'brand' => '',
                'price' => 2,
                'quantity' => 1000,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Nut 5/16',
            ],
            [
                'product_id' => 33,
                'product_name' => 'Bolt',
                'additional_name' => '',
                'type' => '5/16×3/4',
                'brand' => '',
                'price' => 5,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Bolt 5/16×3/4',
            ],
            [
                'product_id' => 34,
                'product_name' => 'Lock Washer',
                'additional_name' => '',
                'type' => '3/8',
                'brand' => '',
                'price' => 2,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Lock Washer 3/8',
            ],
            [
                'product_id' => 35,
                'product_name' => 'Lock Washer',
                'additional_name' => '',
                'type' => '5/16',
                'brand' => '',
                'price' => 2,
                'quantity' => 99,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Lock Washer 5/16',
            ],
            [
                'product_id' => 36,
                'product_name' => 'Washer',
                'additional_name' => '',
                'type' => '5/16',
                'brand' => '',
                'price' => 2,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Washer 5/16',
            ],
            [
                'product_id' => 37,
                'product_name' => 'Washer',
                'additional_name' => '',
                'type' => '3/8',
                'brand' => '',
                'price' => 2,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Washer 3/8',
            ],
            [
                'product_id' => 38,
                'product_name' => 'Washer',
                'additional_name' => '',
                'type' => '5/18',
                'brand' => '',
                'price' => 10,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Washer 5/18',
            ],
            [
                'product_id' => 39,
                'product_name' => 'Nut',
                'additional_name' => '',
                'type' => '1/2',
                'brand' => '',
                'price' => 5,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Nut 1/2',
            ],
            [
                'product_id' => 40,
                'product_name' => 'Nut',
                'additional_name' => '',
                'type' => '1/4',
                'brand' => '',
                'price' => 2,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Nut 1/4',
            ],
            [
                'product_id' => 41,
                'product_name' => 'Bolt',
                'additional_name' => '',
                'type' => '1/4×1',
                'brand' => '',
                'price' => 5,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Bolt 1/4×1',
            ],
            [
                'product_id' => 42,
                'product_name' => 'Bolt',
                'additional_name' => '',
                'type' => '1/2×4',
                'brand' => '',
                'price' => 26,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Bolt 1/2×4',
            ],
            [
                'product_id' => 43,
                'product_name' => 'Lock Bolt',
                'additional_name' => '',
                'type' => '1/2×6',
                'brand' => '',
                'price' => 35,
                'quantity' => 100,
                'location' => 'Shelf A2',
                'image' => '/images/products/bolt.svg',
                'description' => 'Lock Bolt 1/2×6',
            ],
            [
                'product_id' => 44,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6001',
                'brand' => 'Koyo',
                'price' => 120,
                'quantity' => 10,
                'location' => 'Shelf B1',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6001',
            ],
            [
                'product_id' => 45,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6002',
                'brand' => 'Koyo',
                'price' => 150,
                'quantity' => 10,
                'location' => 'Shelf B1',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6002',
            ],
            [
                'product_id' => 46,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6003',
                'brand' => 'Koyo',
                'price' => 150,
                'quantity' => 10,
                'location' => 'Shelf B1',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6003',
            ],
            [
                'product_id' => 47,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6004',
                'brand' => 'Koyo',
                'price' => 150,
                'quantity' => 10,
                'location' => 'Shelf B1',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6004',
            ],
            [
                'product_id' => 48,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6005',
                'brand' => 'Koyo',
                'price' => 170,
                'quantity' => 7,
                'location' => 'Shelf B1',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6005',
            ],
            [
                'product_id' => 49,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6200',
                'brand' => 'Koyo',
                'price' => 100,
                'quantity' => 10,
                'location' => 'Shelf B1',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6200',
            ],
            [
                'product_id' => 50,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6201',
                'brand' => 'Koyo',
                'price' => 120,
                'quantity' => 10,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6201',
            ],
            [
                'product_id' => 51,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6202',
                'brand' => 'Koyo',
                'price' => 120,
                'quantity' => 10,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6202',
            ],
            [
                'product_id' => 52,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6203',
                'brand' => 'Koyo',
                'price' => 140,
                'quantity' => 10,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6203',
            ],
            [
                'product_id' => 53,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6204',
                'brand' => 'Koyo',
                'price' => 180,
                'quantity' => 10,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6204',
            ],
            [
                'product_id' => 54,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6205',
                'brand' => 'Koyo',
                'price' => 180,
                'quantity' => 10,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6205',
            ],
            [
                'product_id' => 55,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6301',
                'brand' => 'Koyo',
                'price' => 150,
                'quantity' => 10,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6301',
            ],
            [
                'product_id' => 56,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6302',
                'brand' => 'Koyo',
                'price' => 150,
                'quantity' => 10,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6302',
            ],
            [
                'product_id' => 57,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6300',
                'brand' => 'Koyo',
                'price' => 100,
                'quantity' => 10,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6300',
            ],
            [
                'product_id' => 58,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6306',
                'brand' => 'Koyo',
                'price' => 320,
                'quantity' => 10,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6306',
            ],
            [
                'product_id' => 59,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '6305',
                'brand' => 'Koyo',
                'price' => 270,
                'quantity' => 10,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 6305',
            ],
            [
                'product_id' => 60,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '607',
                'brand' => 'Koyo',
                'price' => 100,
                'quantity' => 10,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 607',
            ],
            [
                'product_id' => 61,
                'product_name' => 'Bearing',
                'additional_name' => '',
                'type' => '608',
                'brand' => 'Koyo',
                'price' => 100,
                'quantity' => 10,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Bearing 608',
            ],
            [
                'product_id' => 62,
                'product_name' => 'Knuckle Bearing',
                'additional_name' => '',
                'type' => '32207',
                'brand' => 'Koyo',
                'price' => 500,
                'quantity' => 5,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Knuckle Bearing 32207',
            ],
            [
                'product_id' => 63,
                'product_name' => 'Knuckle Bearing',
                'additional_name' => '',
                'type' => '32210',
                'brand' => 'Koyo',
                'price' => 720,
                'quantity' => 5,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Knuckle Bearing 32210',
            ],
            [
                'product_id' => 64,
                'product_name' => 'Knuckle Bearing',
                'additional_name' => '',
                'type' => 'L212641/10',
                'brand' => 'Koyo',
                'price' => 200,
                'quantity' => 5,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Knuckle Bearing L212641/10',
            ],
            [
                'product_id' => 65,
                'product_name' => 'Knuckle Bearing',
                'additional_name' => '',
                'type' => 'LM48548/10',
                'brand' => 'Koyo',
                'price' => 320,
                'quantity' => 5,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Knuckle Bearing LM48548/10',
            ],
            [
                'product_id' => 66,
                'product_name' => 'Knuckle Bearing',
                'additional_name' => '',
                'type' => '45449/10',
                'brand' => 'Koyo',
                'price' => 270,
                'quantity' => 5,
                'location' => 'Shelf B2',
                'image' => '/images/products/bearing.svg',
                'description' => 'Koyo Knuckle Bearing 45449/10',
            ],
            [
                'product_id' => 67,
                'product_name' => 'Fuel Tank cap',
                'additional_name' => '',
                'type' => 'Black',
                'brand' => 'Circuit',
                'price' => 250,
                'quantity' => 100,
                'location' => 'Shelf B1',
                'image' => '/images/products/filter.svg',
                'description' => 'Circuit Fuel Tank cap Black',
            ],
            [
                'product_id' => 68,
                'product_name' => 'Plug-in Fuse',
                'additional_name' => '',
                'type' => '10AMP',
                'brand' => 'Circuit',
                'price' => 10,
                'quantity' => 100,
                'location' => 'Shelf B1',
                'image' => '/images/products/fuse.svg',
                'description' => 'Circuit Plug-in Fuse 10AMP',
            ],
            [
                'product_id' => 69,
                'product_name' => 'Plug-in Fuse',
                'additional_name' => '',
                'type' => '15AMP',
                'brand' => 'Circuit',
                'price' => 10,
                'quantity' => 100,
                'location' => 'Shelf B1',
                'image' => '/images/products/fuse.svg',
                'description' => 'Circuit Plug-in Fuse 15AMP',
            ],
            [
                'product_id' => 70,
                'product_name' => 'Plug-in Fuse',
                'additional_name' => '',
                'type' => '20AMP',
                'brand' => 'Circuit',
                'price' => 10,
                'quantity' => 96,
                'location' => 'Shelf B1',
                'image' => '/images/products/fuse.svg',
                'description' => 'Circuit Plug-in Fuse 20AMP',
            ],
            [
                'product_id' => 71,
                'product_name' => 'Plug-in Fuse',
                'additional_name' => '',
                'type' => '30AMP',
                'brand' => 'Circuit',
                'price' => 10,
                'quantity' => 100,
                'location' => 'Shelf B1',
                'image' => '/images/products/fuse.svg',
                'description' => 'Circuit Plug-in Fuse 30AMP',
            ],
            [
                'product_id' => 72,
                'product_name' => 'Mini Plug-in Fuse',
                'additional_name' => '',
                'type' => '10AMP',
                'brand' => 'Circuit',
                'price' => 10,
                'quantity' => 100,
                'location' => 'Shelf B1',
                'image' => '/images/products/fuse.svg',
                'description' => 'Circuit Mini Plug-in Fuse 10AMP',
            ],
            [
                'product_id' => 73,
                'product_name' => 'Mini Plug-in Fuse',
                'additional_name' => '',
                'type' => '15AMP',
                'brand' => 'Circuit',
                'price' => 10,
                'quantity' => 100,
                'location' => 'Shelf B1',
                'image' => '/images/products/fuse.svg',
                'description' => 'Circuit Mini Plug-in Fuse 15AMP',
            ],
            [
                'product_id' => 74,
                'product_name' => 'Mini Plug-in Fuse',
                'additional_name' => '',
                'type' => '20AMP',
                'brand' => 'Circuit',
                'price' => 10,
                'quantity' => 100,
                'location' => 'Shelf B1',
                'image' => '/images/products/fuse.svg',
                'description' => 'Circuit Mini Plug-in Fuse 20AMP',
            ],
            [
                'product_id' => 75,
                'product_name' => 'Mini Plug-in Fuse',
                'additional_name' => '',
                'type' => '30AMP',
                'brand' => 'Circuit',
                'price' => 10,
                'quantity' => 100,
                'location' => 'Shelf B1',
                'image' => '/images/products/fuse.svg',
                'description' => 'Circuit Mini Plug-in Fuse 30AMP',
            ],
            [
                'product_id' => 76,
                'product_name' => 'Female Terminal',
                'additional_name' => '',
                'type' => '',
                'brand' => 'Circuit',
                'price' => 5,
                'quantity' => 50,
                'location' => 'Shelf B1',
                'image' => '/images/products/electrical.svg',
                'description' => 'Circuit Female Terminal',
            ],
            [
                'product_id' => 77,
                'product_name' => 'Eye Terminal',
                'additional_name' => '',
                'type' => '3/16',
                'brand' => 'Circuit',
                'price' => 5,
                'quantity' => 50,
                'location' => 'Shelf B1',
                'image' => '/images/products/electrical.svg',
                'description' => 'Circuit Eye Terminal 3/16',
            ],
            [
                'product_id' => 78,
                'product_name' => 'Eye Terminal',
                'additional_name' => '',
                'type' => '5/16',
                'brand' => 'Circuit',
                'price' => 10,
                'quantity' => 50,
                'location' => 'Shelf B1',
                'image' => '/images/products/electrical.svg',
                'description' => 'Circuit Eye Terminal 5/16',
            ],
            [
                'product_id' => 79,
                'product_name' => 'Ignition Switch',
                'additional_name' => '',
                'type' => 'Diesel',
                'brand' => 'Circuit',
                'price' => 460,
                'quantity' => 6,
                'location' => 'Shelf B1',
                'image' => '/images/products/electrical.svg',
                'description' => 'Circuit Ignition Switch Diesel',
            ],
            [
                'product_id' => 80,
                'product_name' => 'Ignition Switch',
                'additional_name' => '',
                'type' => 'Gasoline',
                'brand' => 'I.Tokyo',
                'price' => 380,
                'quantity' => 6,
                'location' => 'Shelf B1',
                'image' => '/images/products/electrical.svg',
                'description' => 'I.Tokyo Ignition Switch Gasoline',
            ],
            [
                'product_id' => 81,
                'product_name' => 'Priming Pump',
                'additional_name' => '',
                'type' => '',
                'brand' => 'DENSO',
                'price' => 590,
                'quantity' => 6,
                'location' => 'Shelf B1',
                'image' => '/images/products/electrical.svg',
                'description' => 'DENSO Priming Pump',
            ],
            [
                'product_id' => 82,
                'product_name' => 'Alternator Carbon Brush',
                'additional_name' => '',
                'type' => '37A',
                'brand' => 'FCC',
                'price' => 50,
                'quantity' => 30,
                'location' => 'Shelf B1',
                'image' => '/images/products/electrical.svg',
                'description' => 'FCC Alternator Carbon Brush 37A',
            ],
            [
                'product_id' => 83,
                'product_name' => 'Starter Carbon Brush',
                'additional_name' => '',
                'type' => '4K',
                'brand' => 'FCC',
                'price' => 140,
                'quantity' => 30,
                'location' => 'Shelf B1',
                'image' => '/images/products/electrical.svg',
                'description' => 'FCC Starter Carbon Brush 4K',
            ],
            [
                'product_id' => 84,
                'product_name' => 'Starter Carbon Brush',
                'additional_name' => '',
                'type' => 'L300',
                'brand' => 'FCC',
                'price' => 200,
                'quantity' => 30,
                'location' => 'Shelf B1',
                'image' => '/images/products/electrical.svg',
                'description' => 'FCC Starter Carbon Brush L300',
            ],
            [
                'product_id' => 85,
                'product_name' => 'Alternator Carbon Brush',
                'additional_name' => '',
                'type' => '22A',
                'brand' => 'FCC',
                'price' => 50,
                'quantity' => 30,
                'location' => 'Shelf B1',
                'image' => '/images/products/electrical.svg',
                'description' => 'FCC Alternator Carbon Brush 22A',
            ],
            [
                'product_id' => 86,
                'product_name' => 'Gasket Shellac',
                'additional_name' => '',
                'type' => '',
                'brand' => 'V-tech',
                'price' => 70,
                'quantity' => 50,
                'location' => 'Shelf B1',
                'image' => '/images/products/default.svg',
                'description' => 'V-tech Gasket Shellac',
            ],
            [
                'product_id' => 87,
                'product_name' => 'Temperature Sending Unit',
                'additional_name' => '',
                'type' => '',
                'brand' => 'Circuit',
                'price' => 180,
                'quantity' => 10,
                'location' => 'Shelf B1',
                'image' => '/images/products/electrical.svg',
                'description' => 'Circuit Temperature Sending Unit',
            ],
            [
                'product_id' => 88,
                'product_name' => 'Air-Horn Switch Relay',
                'additional_name' => '',
                'type' => '',
                'brand' => 'Maruzen',
                'price' => 450,
                'quantity' => 6,
                'location' => 'Shelf B1',
                'image' => '/images/products/electrical.svg',
                'description' => 'Maruzen Air-Horn Switch Relay',
            ],
            [
                'product_id' => 89,
                'product_name' => 'Silicon Radiator Cap',
                'additional_name' => '',
                'type' => 'RC-93',
                'brand' => 'Circuit',
                'price' => 120,
                'quantity' => 6,
                'location' => 'Shelf B1',
                'image' => '/images/products/filter.svg',
                'description' => 'Circuit Silicon Radiator Cap RC-93',
            ],
            [
                'product_id' => 90,
                'product_name' => 'Silicon Radiator Cap',
                'additional_name' => '',
                'type' => 'RC-95',
                'brand' => 'Circuit',
                'price' => 120,
                'quantity' => 7,
                'location' => 'Shelf B1',
                'image' => '/images/products/filter.svg',
                'description' => 'Circuit Silicon Radiator Cap RC-95',
            ],
            [
                'product_id' => 91,
                'product_name' => 'Silicon Radiator Cap',
                'additional_name' => '',
                'type' => 'RC-102',
                'brand' => 'Circuit',
                'price' => 120,
                'quantity' => 7,
                'location' => 'Shelf B1',
                'image' => '/images/products/filter.svg',
                'description' => 'Circuit Silicon Radiator Cap RC-102',
            ],
            [
                'product_id' => 92,
                'product_name' => 'Heater Plug',
                'additional_name' => '',
                'type' => '',
                'brand' => 'Circuit',
                'price' => 100,
                'quantity' => 50,
                'location' => 'Shelf B1',
                'image' => '/images/products/electrical.svg',
                'description' => 'Circuit Heater Plug',
            ],
            [
                'product_id' => 93,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-806',
                'brand' => 'ViC',
                'price' => 250,
                'quantity' => 6,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-806',
            ],
            [
                'product_id' => 94,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-415',
                'brand' => 'ViC',
                'price' => 240,
                'quantity' => 6,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-415',
            ],
            [
                'product_id' => 95,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-106',
                'brand' => 'ViC',
                'price' => 250,
                'quantity' => 4,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-106',
            ],
            [
                'product_id' => 96,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-512',
                'brand' => 'ViC',
                'price' => 290,
                'quantity' => 6,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-512',
            ],
            [
                'product_id' => 97,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-312',
                'brand' => 'ViC',
                'price' => 220,
                'quantity' => 6,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-312',
            ],
            [
                'product_id' => 98,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-318',
                'brand' => 'ViC',
                'price' => 950,
                'quantity' => 6,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-318',
            ],
            [
                'product_id' => 99,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-207',
                'brand' => 'ViC',
                'price' => 240,
                'quantity' => 3,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-207',
            ],
            [
                'product_id' => 100,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-527',
                'brand' => 'ViC',
                'price' => 340,
                'quantity' => 6,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-527',
            ],
            [
                'product_id' => 101,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-111',
                'brand' => 'ViC',
                'price' => 280,
                'quantity' => 6,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-111',
            ],
            [
                'product_id' => 102,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-412',
                'brand' => 'ViC',
                'price' => 520,
                'quantity' => 6,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-412',
            ],
            [
                'product_id' => 103,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-707',
                'brand' => 'ViC',
                'price' => 200,
                'quantity' => 6,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-707',
            ],
            [
                'product_id' => 104,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-405',
                'brand' => 'ViC',
                'price' => 250,
                'quantity' => 6,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-405',
            ],
            [
                'product_id' => 105,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-305',
                'brand' => 'ViC',
                'price' => 350,
                'quantity' => 6,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-305',
            ],
            [
                'product_id' => 106,
                'product_name' => 'Oil Filter',
                'additional_name' => '',
                'type' => 'C-503',
                'brand' => 'ViC',
                'price' => 400,
                'quantity' => 6,
                'location' => 'Shelf B2',
                'image' => '/images/products/oil.svg',
                'description' => 'ViC Oil Filter C-503',
            ],
            [
                'product_id' => 107,
                'product_name' => 'Fuel Filter',
                'additional_name' => '',
                'type' => 'FC-193',
                'brand' => 'ViC',
                'price' => 370,
                'quantity' => 6,
                'location' => 'Shelf B3',
                'image' => '/images/products/filter.svg',
                'description' => 'ViC Fuel Filter FC-193',
            ],
            [
                'product_id' => 108,
                'product_name' => 'Fuel Filter',
                'additional_name' => '',
                'type' => 'FC-208A',
                'brand' => 'ViC',
                'price' => 280,
                'quantity' => 6,
                'location' => 'Shelf B3',
                'image' => '/images/products/filter.svg',
                'description' => 'ViC Fuel Filter FC-208A',
            ],
            [
                'product_id' => 109,
                'product_name' => 'Fuel Filter',
                'additional_name' => '',
                'type' => 'FC-317',
                'brand' => 'ViC',
                'price' => 340,
                'quantity' => 6,
                'location' => 'Shelf B3',
                'image' => '/images/products/filter.svg',
                'description' => 'ViC Fuel Filter FC-317',
            ],
            [
                'product_id' => 110,
                'product_name' => 'Rubber Cup',
                'additional_name' => '',
                'type' => 'SC-80353',
                'brand' => '',
                'price' => 55,
                'quantity' => 35,
                'location' => 'Shelf B3',
                'image' => '/images/products/filter.svg',
                'description' => 'Rubber Cup SC-80353',
            ],
            [
                'product_id' => 111,
                'product_name' => 'Rubber Cup',
                'additional_name' => '',
                'type' => 'SC-80423',
                'brand' => '',
                'price' => 50,
                'quantity' => 50,
                'location' => 'Shelf B3',
                'image' => '/images/products/filter.svg',
                'description' => 'Rubber Cup SC-80423',
            ],
            [
                'product_id' => 112,
                'product_name' => 'Rubber Cup',
                'additional_name' => '',
                'type' => 'SC-30233',
                'brand' => '',
                'price' => 60,
                'quantity' => 50,
                'location' => 'Shelf B3',
                'image' => '/images/products/filter.svg',
                'description' => 'Rubber Cup SC-30233',
            ],
            [
                'product_id' => 113,
                'product_name' => 'Rubber Cup',
                'additional_name' => '',
                'type' => 'SC-47624',
                'brand' => '',
                'price' => 50,
                'quantity' => 50,
                'location' => 'Shelf B3',
                'image' => '/images/products/filter.svg',
                'description' => 'Rubber Cup SC-47624',
            ],
            [
                'product_id' => 114,
                'product_name' => 'Electrical Tape',
                'additional_name' => '',
                'type' => 'Big',
                'brand' => 'Armok',
                'price' => 60,
                'quantity' => 20,
                'location' => 'Shelf B4',
                'image' => '/images/products/electrical.svg',
                'description' => 'Armok Electrical Tape Big',
            ],
            [
                'product_id' => 115,
                'product_name' => 'Electrical Tape',
                'additional_name' => '',
                'type' => 'Small',
                'brand' => 'Armok',
                'price' => 30,
                'quantity' => 20,
                'location' => 'Shelf B4',
                'image' => '/images/products/electrical.svg',
                'description' => 'Armok Electrical Tape Small',
            ],
            [
                'product_id' => 116,
                'product_name' => 'Spray Paint',
                'additional_name' => '',
                'type' => 'Silver',
                'brand' => 'Bosny',
                'price' => 120,
                'quantity' => 5,
                'location' => 'Shelf C1',
                'image' => '/images/products/spray-paint.svg',
                'description' => 'Bosny Spray Paint Silver',
            ],
            [
                'product_id' => 117,
                'product_name' => 'Spray Paint',
                'additional_name' => '',
                'type' => 'Black',
                'brand' => 'Bosny',
                'price' => 120,
                'quantity' => 5,
                'location' => 'Shelf C1',
                'image' => '/images/products/spray-paint.svg',
                'description' => 'Bosny Spray Paint Black',
            ],
            [
                'product_id' => 118,
                'product_name' => 'Spray Paint',
                'additional_name' => '',
                'type' => 'White',
                'brand' => 'Bosny',
                'price' => 120,
                'quantity' => 5,
                'location' => 'Shelf C1',
                'image' => '/images/products/spray-paint.svg',
                'description' => 'Bosny Spray Paint White',
            ],
            [
                'product_id' => 119,
                'product_name' => 'Spray Paint',
                'additional_name' => '',
                'type' => 'Clear',
                'brand' => 'Bosny',
                'price' => 120,
                'quantity' => 5,
                'location' => 'Shelf C1',
                'image' => '/images/products/spray-paint.svg',
                'description' => 'Bosny Spray Paint Clear',
            ],
            [
                'product_id' => 120,
                'product_name' => 'Spray Paint',
                'additional_name' => '',
                'type' => 'Blue',
                'brand' => 'Bosny',
                'price' => 120,
                'quantity' => 6,
                'location' => 'Shelf C1',
                'image' => '/images/products/spray-paint.svg',
                'description' => 'Bosny Spray Paint Blue',
            ],
            [
                'product_id' => 121,
                'product_name' => 'Spray Paint',
                'additional_name' => '',
                'type' => 'Red',
                'brand' => 'Bosny',
                'price' => 120,
                'quantity' => 5,
                'location' => 'Shelf C1',
                'image' => '/images/products/spray-paint.svg',
                'description' => 'Bosny Spray Paint Red',
            ],
            [
                'product_id' => 122,
                'product_name' => 'Spray Paint',
                'additional_name' => '',
                'type' => 'Yellow',
                'brand' => 'Bosny',
                'price' => 120,
                'quantity' => 5,
                'location' => 'Shelf C1',
                'image' => '/images/products/spray-paint.svg',
                'description' => 'Bosny Spray Paint Yellow',
            ],
            [
                'product_id' => 123,
                'product_name' => 'Battery Terminal',
                'additional_name' => '',
                'type' => '',
                'brand' => '',
                'price' => 70,
                'quantity' => 245,
                'location' => 'Shelf B4',
                'image' => '/images/products/electrical.svg',
                'description' => 'Battery Terminal',
            ],
            [
                'product_id' => 124,
                'product_name' => 'Sandpaper',
                'additional_name' => '',
                'type' => 'CC 120',
                'brand' => 'Hippo',
                'price' => 20,
                'quantity' => 100,
                'location' => 'Shelf C5',
                'image' => '/images/products/default.svg',
                'description' => 'Hippo Sandpaper CC 120',
            ],
            [
                'product_id' => 125,
                'product_name' => 'Sandpaper',
                'additional_name' => '',
                'type' => 'CC 400',
                'brand' => 'Hippo',
                'price' => 20,
                'quantity' => 100,
                'location' => 'Shelf C5',
                'image' => '/images/products/default.svg',
                'description' => 'Hippo Sandpaper CC 400',
            ],
            [
                'product_id' => 126,
                'product_name' => 'Sandpaper',
                'additional_name' => '',
                'type' => 'CC 1000',
                'brand' => 'Hippo',
                'price' => 20,
                'quantity' => 96,
                'location' => 'Shelf C5',
                'image' => '/images/products/default.svg',
                'description' => 'Hippo Sandpaper CC 1000',
            ],
        ];

        foreach ($products as $p) {
            Product::updateOrCreate(
                ['product_id' => $p['product_id']],
                $p
            );
        }
    }
}
